import { Award, Code2, Download, GraduationCap, Heart, MapPin, Mail, Phone } from 'lucide-react';
import AmbientField from '../components/AmbientField';
import Button from '../components/Button';
import PageShell from '../components/PageShell';
import Reveal from '../components/Reveal';
import SectionHeading from '../components/SectionHeading';
import SEO from '../components/SEO';
import TechBadge from '../components/TechBadge';
import { certifications, skills } from '../data/site';

const qualifications = ['Builds responsive websites with HTML, CSS, and JavaScript.', 'Knowledge of both front-end and back-end web development.', 'Experience creating personal and group projects with modern web tools.', 'A fast learner committed to continually improving development skills.'];
const codingHobbies = ['Practicing programming languages', 'Building and improving personal web projects', 'Exploring new web technologies', 'Learning through coding platforms and documentation', 'Improving website performance and responsiveness'];
export default function Resume() {
  return <PageShell><SEO title="Resume | Kris Dane Madlambayan" description="View the education, qualifications, technical expertise, achievements, and freeCodeCamp certifications of web developer Kris Dane Madlambayan." image="/assets/resumepicture.webp" />
    <section className="page-hero resume-hero"><AmbientField compact /><div className="container resume-heading"><span className="page-index-mark">04 / 05</span><div><p className="eyebrow"><span />Résumé</p><h1>Developer mindset.<br /><em>Designer&apos;s eye.</em></h1><p>Aspiring Web Developer and Front-End Specialist focused on responsive, accessible, and intuitive interfaces.</p><div className="resume-contact"><a href="mailto:krisdane1234@gmail.com"><Mail />krisdane1234@gmail.com</a><a href="tel:+639954834034"><Phone />0995 483 4034</a><span><MapPin />Sindalan, San Fernando City, Pampanga</span></div></div><div className="resume-photo"><img src="/assets/resumepicture.webp" alt="Kris Dane Madlambayan" width="863" height="1104" /></div></div></section>
    <section className="section"><div className="container"><Reveal className="summary-card"><p className="eyebrow"><span />Professional summary</p><p>Aspiring Web Developer and Front-End Specialist passionate about building responsive, accessible, and intuitive user interfaces. Eager to apply modern web development and user-centered design skills to create thoughtful web solutions that improve digital services and streamline processes. Committed to continuous growth and high-quality work in collaborative, fast-paced environments.</p></Reveal></div></section>
    <section className="section surface-section"><div className="container resume-two-col"><div><SectionHeading eyebrow="Qualifications" title="What I bring." /><div className="qualification-list">{qualifications.map((item, index) => <Reveal key={item} className="qualification"><span>{String(index + 1).padStart(2, '0')}</span><p>{item}</p></Reveal>)}</div></div><Reveal className="education-card"><GraduationCap /><p className="eyebrow">Education</p><h3>Bachelor of Science in Information Technology</h3><strong>Holy Angel University</strong><p>Angeles City, Pampanga<br />2023 — Present</p><div className="achievement"><Award size={18} /><span>Dean&apos;s Lister<br /><small>2024 — Present</small></span></div><p className="coursework">Coursework: Web Development, UI/UX Design, System Analysis & Design, and Database Fundamentals.</p></Reveal></div></section>
    <section className="section"><div className="container skills-layout"><SectionHeading eyebrow="Technical expertise" title="A growing development toolkit." /><Reveal className="skill-panel">{skills.map((skill) => <TechBadge key={skill}>{skill}</TechBadge>)}</Reveal></div></section>
    <section className="section surface-section"><div className="container"><SectionHeading eyebrow="Credentials" title="Certifications and continued learning." /><div className="cert-grid">{certifications.map((cert, index) => <Reveal className="cert-card" key={cert.title} delay={index * .06}><div className="cert-top"><span>0{index + 1}</span><Award /></div><p className="cert-issuer">{cert.issuer}</p><h3>{cert.title}</h3><p>{cert.description}</p><div className="cert-footer"><time>{cert.date}</time><a href={cert.url} target="_blank" rel="noopener noreferrer">View certificate ↗</a></div></Reveal>)}</div></div></section>
    <section className="section"><div className="container"><SectionHeading eyebrow="Beyond coursework" title="Interests that keep me learning." /><div className="interests-grid"><Reveal className="interest-card"><Code2 /><h3>Programming-related</h3><ul>{codingHobbies.map((item) => <li key={item}>{item}</li>)}</ul></Reveal><Reveal className="interest-card" delay={.08}><Heart /><h3>Outside technology</h3><ul><li>Playing basketball</li><li>Playing games</li><li>Watching movies</li><li>Spending time with friends and family</li></ul></Reveal></div></div></section>
    <section className="section"><div className="container download-panel"><div><p className="eyebrow"><Download size={16} />Downloads</p><h2>Take my résumé with you.</h2><p>Choose the format that works best for your review.</p></div><div className="download-actions"><Button href="/downloads/resume.pdf" download="Kris-Dane-Madlambayan-Resume.pdf">PDF</Button><Button href="/downloads/resume.docx" download="Kris-Dane-Madlambayan-Resume.docx" variant="secondary">DOCX</Button><Button href="/downloads/resume.png" download="Kris-Dane-Madlambayan-Resume.png" variant="secondary">Image</Button></div></div></section>
  </PageShell>;
}
